[tool.poetry]
name = "grid-world-ai"
version = "0.1.0"
description = ""
authors = ["rakin406"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
raylib = "^5.0.0.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
